import datetime


def get_all(time_select):
    get_all_data_from_postgre = ("select * from (SELECT fw.type,\n"
                                 "       fw.created,\n"
                                 "       fw.modified,\n"
                                 "\n"
                                 "       fw.id,\n"
                                 "       fw.rating                  as imdb_rating,\n"
                                 "       array_agg(DISTINCT g.name) as genre,\n"
                                 "       fw.title,\n"
                                 "       fw.description,\n"
                                 "\n"
                                 "       coalesce(\n"
                                 "                       array_agg(\n"
                                 "                       DISTINCT p.full_name\n"
                                 "                   )\n"
                                 "                       filter (WHERE pfw.role is not null and pfw.role = 'director')\n"
                                 "           , '{}'\n"
                                 "           )                      as director,\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "        coalesce(\n"
                                 "                       array_agg(\n"
                                 "                       DISTINCT p.full_name\n"
                                 "                   )\n"
                                 "                       filter (WHERE pfw.role is not null and pfw.role = 'actor')\n"
                                 "           , '{}'\n"
                                 "           )\n"
                                 "                                  as actors_names,\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "           coalesce(\n"
                                 "                       array_agg(\n"
                                 "                       DISTINCT p.full_name\n"
                                 "                   )\n"
                                 "                       filter (WHERE pfw.role is not null and pfw.role = 'writer')\n"
                                 "           , '{}'\n"
                                 "           )                      as writers_names,\n"
                                 "\n"
                                 "       COALESCE(\n"
                                 "                       json_agg(\n"
                                 "                       DISTINCT jsonb_build_object(\n"
                                 "                               'id', p.id,\n"
                                 "                               'name', p.full_name\n"
                                 "                           )\n"
                                 "                   ) FILTER (WHERE p.id is not null and pfw.role = 'actor'),\n"
                                 "                       '[]'\n"
                                 "           )                      as actors,\n"
                                 "\n"
                                 "\n"
                                 "       COALESCE(\n"
                                 "                       json_agg(\n"
                                 "                       DISTINCT jsonb_build_object(\n"
                                 "                               'id', p.id,\n"
                                 "                               'name', p.full_name\n"
                                 "                           )\n"
                                 "                   ) FILTER (WHERE p.id is not null and pfw.role = 'writer'),\n"
                                 "                       '[]'\n"
                                 "           )                      as writers\n"
                                 "\n"
                                 "FROM content.film_work fw\n"
                                 "         LEFT JOIN content.person_film_work pfw\n"
                                 "                   ON pfw.film_work_id = fw.id\n"
                                 "         LEFT JOIN content.person p ON p.id = pfw.person_id\n"
                                 "         LEFT JOIN content.genre_film_work gfw ON gfw.film_work_id = fw.id\n"
                                 "         LEFT JOIN content.genre g ON g.id = gfw.genre_id\n"
                                 f"WHERE fw.modified<'{time_select}'"
                                 "GROUP BY fw.id\n"
                                 "ORDER BY fw.modified) fppgg;\n")
    return get_all_data_from_postgre
